version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: tt_server
    container_name: tt_server
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "9230:9229"
    depends_on:
      - db

  db:
    image: postgres:11
    container_name: tt_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5434:5432"
